# #############################################################################
# L3: Simple Makefile to build and test Lightweight Logging Library sources
#
# Developed based on SplinterDB (https://github.com/vmware/splinterdb) Makefile
# Modelled on the lines of the Makefile of the LineOfCode project, with which
# L3 will be integrated (See: https://github.com/Soft-Where-Inc/LineOfCode)
#
# This repo contains the core L3 library files: l3.h l3.c, l3.S (assembly)
# It contains test-use-case in C and C++. The core L3 objects have to be
# separately linked with both the C and C++ use-case sample programs.
#
# Therefore, this Makefile is written in a way to compile both the C and C++
# sources with gcc and g++ compilers, respectively. To allow linking the .S
# assembly file with C++ sources, we have to compile l3.c also with C++
# compilers.
#
# Thus, this Makefile provides two separate targets:
#   - Build     : all-c_tests and all-cpp-tests
#   - Run Tests : run-c-tests and run-cpp-tests
#
# to be able to compile
# \copyright Copyright (c) 2024
# #############################################################################

.DEFAULT_GOAL := all

help::
	@echo 'You need multiple invocations in this series to build all sources:'
	@echo ' '
	@echo 'Usage:'
	@echo ' '
	@echo 'To build C-sample programs and run unit-tests:'
	@echo ' make clean && CC=gcc LD=g++ make all-c-tests'
	@echo ' make run-c-tests'
	@echo ' '
	@echo 'To build C++-sample programs and run unit-tests:'
	@echo ' make clean-l3 && CC=g++ CXX=g++ LD=g++ make all-cpp-tests'
	@echo ' make run-cpp-tests'
	@echo ' '
	@echo 'To build C++-sample .cc programs and run unit-tests:'
	@echo ' make clean-l3 && CC=g++ CXX=g++ LD=g++ make all-cc-tests'
	@echo ' make run-cc-tests'
	@echo ' '
	@echo 'Environment variables: '
	@echo ' BUILD_MODE={release,debug}'
	@echo ' BUILD_VERBOSE={0,1}'

#
# Verbosity
#
ifndef BUILD_VERBOSE
   BUILD_VERBOSE=0
endif

# Setup echo formatting for messages.
ifeq "$(BUILD_VERBOSE)" "1"
   COMMAND=
   PROLIX=@echo
   BRIEF=@ >/dev/null echo
   # Always print message describe step executed, even in verbose mode.
   # BRIEF_FORMATTED=@ >/dev/null echo
   BRIEF_FORMATTED=@printf
   BRIEF_PARTIAL=@echo -n >/dev/null
else ifeq "$(BUILD_VERBOSE)" "0"
   COMMAND=@
   PROLIX=@ >/dev/null echo
   BRIEF=@echo
   BRIEF_FORMATTED=@printf
   BRIEF_PARTIAL=@echo -n
else
   $(error Unknown BUILD_VERBOSE mode "$(BUILD_VERBOSE)".  Valid values are "0" or "1". Default is "0")
endif

# Compilers to use
CC  ?= gcc
CXX ?= g++
LD  ?= gcc

# ###################################################################
# SOURCE DIRECTORIES AND FILES, Generator Package
# ###################################################################
#
L3PACKAGE   = l3
SRCDIR      = src
INCDIR      = include
L3_SRCDIR   = $(SRCDIR)
L3_INCDIR   = $(INCDIR)
TESTSDIR    = test-use-cases

# ###################################################################
# BUILD DIRECTORIES AND FILES
# ###################################################################
#
ifndef BUILD_ROOT
   BUILD_ROOT := build
endif

#
# Build mode
#
ifndef BUILD_MODE
   BUILD_MODE=release
endif
BUILD_DIR := $(BUILD_MODE)

BUILD_PATH=$(BUILD_ROOT)/$(BUILD_DIR)

OBJDIR = $(BUILD_PATH)/obj
BINDIR = $(BUILD_PATH)/bin

# ###################################################################
# SOURCE DIRECTORIES AND FILES
# ###################################################################

L3_SRC      := $(L3_SRCDIR)/l3.c
L3_ASSEMBLY := l3.S
L3_SRCS     := $(L3_SRC) $(L3_ASSEMBLY)

# ###################################################################
# Symbols for test-case data files generated by sample programs
# ###################################################################
TMPDIR              := /tmp
TEST_DATA_SUFFIX    := test.dat

L3_C_DATA           := $(TMPDIR)/$(L3PACKAGE).c-$(TEST_DATA_SUFFIX)
L3_C_SMALL_DATA     := $(TMPDIR)/$(L3PACKAGE).c-small-$(TEST_DATA_SUFFIX)
L3_CPP_DATA         := $(TMPDIR)/$(L3PACKAGE).cpp-$(TEST_DATA_SUFFIX)
L3_CPP_SMALL_DATA   := $(TMPDIR)/$(L3PACKAGE).cpp-small-$(TEST_DATA_SUFFIX)
L3_CC_DATA          := $(TMPDIR)/$(L3PACKAGE).cc-$(TEST_DATA_SUFFIX)
L3_CC_SMALL_DATA    := $(TMPDIR)/$(L3PACKAGE).cc-small-$(TEST_DATA_SUFFIX)

# ###################################################################
# ---- Symbols to build test-code sample programs
# ###################################################################

# -- Pick-up both C and C++ sources in separate lists, named by a symbol.
TEST_C_CODE_SRC := $(shell find $(L3_SRCDIR) $(TESTSDIR) -type f \( -name *.c \) -print)

# Need to pick-up l3.c also. (Support both *.cpp and *.cc for C++).
TEST_CPP_CODE_SRC := $(shell find $(L3_SRCDIR) $(TESTSDIR) -type f \( -name l3.c -o -name *.cpp -o -name *.cc \) -print)
TEST_CC_CODE_SRC  := $(shell find $(L3_SRCDIR) $(TESTSDIR) -type f \( -name l3.c -o -name *.cc -o -name *.cc \) -print)

# Uncomment this to see symbol, for debugging.
# $(info $$TEST_C_CODE_SRC     = [${TEST_C_CODE_SRC} ])
# $(info $$TEST_CPP_CODE_SRC   = [${TEST_CPP_CODE_SRC} ])

# ----------------------------------------------------------------------------
# Generate location / name of test-use-cases sample program binary, using
# built-in substitution references. test-use-cases/ has sources like:
#
#   test-use-cases/single-file-C-program/test-main.c
#   test-use-cases/single-file-Cpp-program/test-main.cpp
#
# Convert this list of *main.c to generate test-code program binary names,
# using the src-dir's name as the program name.
#
# Generate, respectively:
#
#   build/release/bin/test-use-cases/single-file-C-program
#   build/release/bin/test-use-cases/single-file-Cpp-program
#
TEST_C_CODE_BINS_TMP := $(TEST_C_CODE_SRC:$(TESTSDIR)/%-main.c=$(BINDIR)/$(TESTSDIR)/%-program)
TEST_C_CODE_BINS=$(patsubst %program/, %program, $(dir $(TEST_C_CODE_BINS_TMP)) )

# Uncomment this to see symbol, for debugging.
# $(info $$TEST_C_CODE_BINS     = [${TEST_C_CODE_BINS} ])

TEST_CPP_CODE_BINS_TMP := $(TEST_CPP_CODE_SRC:$(TESTSDIR)/%-main.cpp=$(BINDIR)/$(TESTSDIR)/%-program)
TEST_CPP_CODE_BINS_TMP := $(TEST_CPP_CODE_BINS_TMP:$(TESTSDIR)/%-main.cc=$(BINDIR)/$(TESTSDIR)/%-program)
TEST_CPP_CODE_BINS=$(patsubst %program/, %program, $(dir $(TEST_CPP_CODE_BINS_TMP)) )

TEST_CC_CODE_BINS_TMP := $(TEST_CPP_CODE_SRC:$(TESTSDIR)/%-main.cpp=$(BINDIR)/$(TESTSDIR)/%-program)
TEST_CC_CODE_BINS_TMP := $(TEST_CPP_CODE_BINS_TMP:$(TESTSDIR)/%-main.cc=$(BINDIR)/$(TESTSDIR)/%-program)
TEST_CC_CODE_BINS=$(patsubst %program/, %program, $(dir $(TEST_CPP_CODE_BINS_TMP)) )

# Uncomment this to see symbol, for debugging.
# $(info $$TEST_CPP_CODE_BINS     = [${TEST_CPP_CODE_BINS} ])

# Build symbol for single C & C++ unit-test binary that we run
C_UNIT_TEST_BIN     := $(BUILD_ROOT)/$(BUILD_MODE)/bin/test-use-cases/single-file-C-program
CPP_UNIT_TEST_BIN   := $(BUILD_ROOT)/$(BUILD_MODE)/bin/test-use-cases/single-file-Cpp-program
CC_UNIT_TEST_BIN    := $(BUILD_ROOT)/$(BUILD_MODE)/bin/test-use-cases/single-file-CC-program

# ###################################################################
# Report build machine details and compiler version for troubleshooting,
# so we see this output for clean builds, especially in CI-jobs.
# ###################################################################
.PHONY : clean tags
clean:
	uname -a
	$(CC) --version
	rm -rf $(BUILD_ROOT)

# Delete l3.o object as it needs to be recompiled for inclusion w/C++ sources
clean-l3:
	rm -rf $(OBJDIR)/src/l3.o

# ###################################################################
# Make build targets begin here
# ###################################################################

all-c-tests:   $(TEST_C_CODE_BINS)
all-cpp-tests: $(TEST_CPP_CODE_BINS)
all-cc-tests:  $(TEST_CC_CODE_BINS)

# ###################################################################
# CFLAGS, LDFLAGS, ETC
# ###################################################################
#

# -----------------------------------------------------------------------------
# Define the include files' dir-path.
# -----------------------------------------------------------------------------
INCLUDE = -I ./$(L3_INCDIR)
INCLUDE += -I ./$(dir $<)

# use += here, so that extra flags can be provided via the environment

# CFLAGS += -D_GNU_SOURCE -ggdb3 -Wall -Wfatal-errors -Werror
CFLAGS += -D_GNU_SOURCE -ggdb3 -Wall -Wfatal-errors -Werror

# ###################################################################
# Automatically create directories, based on
# http://ismail.badawi.io/blog/2017/03/28/automatic-directory-creation-in-make/
# ###################################################################
#
.SECONDEXPANSION:

.SECONDARY:

%/.:
	$(COMMAND) mkdir -p $@

# These targets prevent circular dependencies arising from the
# recipe for building binaries
$(BINDIR)/.:
	$(COMMAND) mkdir -p $@

$(BINDIR)/%/.:
	$(COMMAND) mkdir -p $@

# ###################################################################
# The dependencies for each test-use-cases/ sample program.
# Every example program of the form bin/test-use-cases/<eg-prog> depends on
# obj/test-use-cases/<eg-prog>/*.o -> *.c
# There can be more than one .o's linked to create test-use-cases example
# program.

# ----
SINGLE_FILE_C_PROGRAM_TESTSRC := $(shell find $(TESTSDIR)/single-file-C-program -type f -name *.c -print)

SINGLE_FILE_C_PROGRAM_TESTSRC += $(L3_SRCS)

SINGLE_FILE_C_PROGRAM_OBJS := $(SINGLE_FILE_C_PROGRAM_TESTSRC:%.c=$(OBJDIR)/%.o)

$(BINDIR)/$(TESTSDIR)/single-file-C-program: $(SINGLE_FILE_C_PROGRAM_OBJS)

# ----
SINGLE_FILE_CPP_PROGRAM_TESTSRC := $(shell find $(TESTSDIR)/single-file-Cpp-program -type f -name *.cpp -print)
SINGLE_FILE_CPP_PROGRAM_TESTSRC += $(L3_SRCS)

# For C++ sources, have to go back and replace l3.c -> l3.o
SINGLE_FILE_CPP_PROGRAM_OBJS := $(SINGLE_FILE_CPP_PROGRAM_TESTSRC:%.cpp=$(OBJDIR)/%.o)
SINGLE_FILE_CPP_PROGRAM_OBJS := $(SINGLE_FILE_CPP_PROGRAM_OBJS:%.c=$(OBJDIR)/%.o)

$(BINDIR)/$(TESTSDIR)/single-file-Cpp-program: $(SINGLE_FILE_CPP_PROGRAM_OBJS)

# ----
SINGLE_FILE_CC_PROGRAM_TESTSRC := $(shell find $(TESTSDIR)/single-file-CC-program -type f -name *.cc -print)
SINGLE_FILE_CC_PROGRAM_TESTSRC += $(L3_SRCS)

# For C++ sources, have to go back and replace l3.c -> l3.o
SINGLE_FILE_CC_PROGRAM_OBJS := $(SINGLE_FILE_CC_PROGRAM_TESTSRC:%.cc=$(OBJDIR)/%.o)
SINGLE_FILE_CC_PROGRAM_OBJS := $(SINGLE_FILE_CC_PROGRAM_OBJS:%.c=$(OBJDIR)/%.o)

$(BINDIR)/$(TESTSDIR)/single-file-CC-program: $(SINGLE_FILE_CC_PROGRAM_OBJS)

# ###################################################################
# RECIPES:
# ###################################################################
#
# For all-test-code, we need to use -I test-code/<subdir>
# Dependencies for the main executables
COMPILE.c   = $(CC)  $(CFLAGS) $(INCLUDE) -c
COMPILE.cpp = $(CXX) $(CFLAGS) $(INCLUDE) -c
COMPILE.cc  = $(CXX) $(CFLAGS) $(INCLUDE) -c

# Compile each .c file into its .o
# Also define a dependency on the dir in which .o will be produced (@D).
# The secondary expansion will invoke mkdir to create output dirs first.
$(OBJDIR)/%.o: %.c | $$(@D)/.
	$(BRIEF_FORMATTED) "%-20s %-50s [%s]\n" Compiling $< $@
	$(COMMAND) $(COMPILE.c) $< -o $@
	$(PROLIX) # blank line

# Compile each .cpp file into its .o
$(OBJDIR)/%.o: %.cpp | $$(@D)/.
	$(BRIEF_FORMATTED) "%-20s %-50s [%s]\n" Compiling $< $@
	$(COMMAND) $(COMPILE.cpp) $< -o $@
	$(PROLIX) # blank line

# Compile each .cc file into its .o
$(OBJDIR)/%.o: %.cc | $$(@D)/.
	$(BRIEF_FORMATTED) "%-20s %-50s [%s]\n" Compiling $< $@
	$(COMMAND) $(COMPILE.cpp) $< -o $@
	$(PROLIX) # blank line

# Link .o's to produce running binary
# Define dependency on output dir existing, so secondary expansion will
# trigger mkdir to create bin/s output dir.
# If you add "$^" to 'Linking' message, you will see list of .o's being linked
$(BINDIR)/%: | $$(@D)/.
	$(BRIEF_FORMATTED) "%-20s %s\n" Linking $@
	$(COMMAND) $(LD) $(LDFLAGS) $^ -o $@ $(LIBS)
	$(PROLIX) # blank line

#*************************************************************#
# Testing: Make test targets
#*************************************************************#
#

.PHONY: install

run-c-tests: all-c-tests
	pylint l3_dump.py
	./$(C_UNIT_TEST_BIN)
	@echo
	./l3_dump.py
	@echo
	python3 l3_dump.py $(L3_C_DATA) ./$(C_UNIT_TEST_BIN)
	@echo
	python3 l3_dump.py $(L3_C_SMALL_DATA) ./$(C_UNIT_TEST_BIN)

run-cpp-tests: all-cpp-tests
	./$(CPP_UNIT_TEST_BIN)
	@echo
	./l3_dump.py
	@echo
	python3 l3_dump.py $(L3_CPP_DATA) ./$(CPP_UNIT_TEST_BIN)
	@echo
	python3 l3_dump.py $(L3_CPP_SMALL_DATA) ./$(CPP_UNIT_TEST_BIN)

run-cc-tests: all-cc-tests
	./$(CC_UNIT_TEST_BIN)
	@echo
	./l3_dump.py
	@echo
	python3 l3_dump.py $(L3_CC_DATA) ./$(CC_UNIT_TEST_BIN)
	@echo
	python3 l3_dump.py $(L3_CC_SMALL_DATA) ./$(CC_UNIT_TEST_BIN)

# ###################################################################
#
test-old: test-use-cases/single-file-C-program/test-main.c src/l3.c l3.S include/l3.h
	pylint l3_dump.py
	g++ -I./include -Wall -o test -g -O3 -D_GNU_SOURCE test-use-cases/single-file-C-program/test-main.c src/l3.c l3.S
	./test
	@echo
	./l3_dump.py
	@echo
	python3 l3_dump.py /tmp/l3_test ./test
	@echo
	python3 l3_dump.py /tmp/l3_small_test ./test
